# Generated by Django 4.2.17 on 2025-01-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
            ],
        ),
    ]
