# Generated by Django 4.2.17 on 2025-01-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0002_abilities_datasheets_datasheetsleader_lastupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetsstratagems',
            name='datasheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratagems', to='army_details.datasheets'),
        ),
        migrations.CreateModel(
            name='Stratagems',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type_char', models.CharField(max_length=1000)),
                ('cp_cost', models.IntegerField()),
                ('legend', models.CharField()),
                ('turn', models.CharField()),
                ('phase', models.CharField()),
                ('detachment', models.CharField()),
                ('description', models.CharField()),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratagems', to='army_details.factions')),
            ],
        ),
        migrations.AlterField(
            model_name='datasheetsstratagems',
            name='strategem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to='army_details.stratagems'),
        ),
        migrations.DeleteModel(
            name='Strategems',
        ),
    ]
