# Generated by Django 4.2.17 on 2025-01-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0003_alter_datasheetsstratagems_datasheet_id_stratagems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factions',
            name='id',
            field=models.CharField(blank=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
