# Generated by Django 4.2.17 on 2025-01-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0004_alter_factions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratagems',
            name='main',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stratagems', to='army_details.factions'),
        ),
    ]
