# Generated by Django 4.2.17 on 2025-01-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0010_alter_detachmentabilities_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheets',
            name='damaged_descp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='damaged_w',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='faction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasheet_factions', to='army_details.factions'),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='leader_footer',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='leader_head',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='legend',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='loadout',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='role',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_datasheets', to='army_details.source'),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='transport',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheets',
            name='virtual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
