# Generated by Django 4.2.17 on 2025-01-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0011_alter_datasheets_damaged_descp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheets',
            old_name='faction_id',
            new_name='faction',
        ),
        migrations.RenameField(
            model_name='datasheets',
            old_name='source_id',
            new_name='source',
        ),
    ]
