# Generated by Django 4.2.17 on 2025-01-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0012_rename_faction_id_datasheets_faction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetsabilities',
            name='ability_id',
        ),
        migrations.RemoveField(
            model_name='datasheetsabilities',
            name='main',
        ),
        migrations.AddField(
            model_name='datasheetsabilities',
            name='abilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ability_id', to='army_details.abilities'),
        ),
        migrations.AddField(
            model_name='datasheetsabilities',
            name='datasheets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abilities_set', to='army_details.datasheets'),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='model',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='parameter',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='type_char',
            field=models.CharField(blank=True, null=True),
        ),
    ]
