# Generated by Django 4.2.17 on 2025-01-13 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0015_alter_abilities_abilities_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilities',
            name='abilities_id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='datasheetsabilities',
            name='abilities',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsdetachmentabilities',
            name='detachment_abilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasheets', to='army_details.detachmentabilities'),
        ),
    ]
