# Generated by Django 4.2.17 on 2025-01-13 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0017_rename_abilities_datasheetsabilities_abilities_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetskeyword',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faction_keywords', to='army_details.datasheets'),
        ),
    ]
