# Generated by Django 4.2.17 on 2025-01-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0018_alter_datasheetskeyword_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_details', to='army_details.datasheets'),
        ),
    ]
