# Generated by Django 4.2.17 on 2025-01-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0019_alter_datasheetsmodels_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='base_size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='base_size_desc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='invul_save',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='invul_save_descr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='leadership',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='move',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='obj_control',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='toughness',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasheetsmodels',
            name='wounds',
            field=models.CharField(blank=True, null=True),
        ),
    ]
