# Generated by Django 4.2.17 on 2025-01-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0020_alter_datasheetsmodels_base_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetsmodels',
            name='save',
            field=models.CharField(blank=True, null=True),
        ),
    ]
