# Generated by Django 4.2.17 on 2025-01-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0021_datasheetsmodels_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasheetsModels',
        ),
    ]
