# Generated by Django 4.2.17 on 2025-01-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0022_delete_datasheetsmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasheetsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('move', models.CharField(blank=True, null=True)),
                ('toughness', models.CharField(blank=True, null=True)),
                ('save', models.CharField(blank=True, null=True)),
                ('invul_save', models.CharField(blank=True, null=True)),
                ('invul_save_descr', models.CharField(blank=True, null=True)),
                ('wounds', models.CharField(blank=True, null=True)),
                ('leadership', models.CharField(blank=True, null=True)),
                ('obj_control', models.CharField(blank=True, null=True)),
                ('base_size', models.CharField(blank=True, null=True)),
                ('base_size_desc', models.CharField(blank=True, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_details', to='army_details.datasheets')),
            ],
        ),
    ]
