# Generated by Django 4.2.17 on 2025-01-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0023_datasheetsmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheetsmodels',
            old_name='save',
            new_name='save_char',
        ),
    ]
