# Generated by Django 4.2.17 on 2025-01-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0024_rename_save_datasheetsmodels_save_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetsoptions',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_options', to='army_details.datasheets'),
        ),
    ]
