# Generated by Django 4.2.17 on 2025-01-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0025_alter_datasheetsoptions_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetswargear',
            name='armour_pen',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='attacks',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='bs_ws',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='damage',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='dice',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wargear', to='army_details.datasheets'),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='range_char',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datasheetswargear',
            name='strength',
            field=models.CharField(),
        ),
    ]
