# Generated by Django 4.2.17 on 2025-01-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0026_alter_datasheetswargear_armour_pen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetsunitcomp',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_compisitions', to='army_details.datasheets'),
        ),
        migrations.AlterField(
            model_name='datashetsmodelscost',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_cost', to='army_details.datasheets'),
        ),
    ]
