# Generated by Django 4.2.17 on 2025-01-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0027_alter_datasheetsunitcomp_main_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatashetsModelsCost',
            new_name='DatasheetsModelsCost',
        ),
    ]
