# Generated by Django 4.2.17 on 2025-01-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0028_rename_datashetsmodelscost_datasheetsmodelscost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheetsmodelscost',
            name='cost',
            field=models.CharField(),
        ),
    ]
