# Generated by Django 4.2.17 on 2025-01-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0029_alter_datasheetsmodelscost_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheetsstratagems',
            old_name='datasheet_id',
            new_name='datasheet',
        ),
        migrations.RenameField(
            model_name='datasheetsstratagems',
            old_name='strategem_id',
            new_name='stratagem',
        ),
    ]
