# Generated by Django 4.2.17 on 2025-01-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0031_rename_datasheet_id_datasheetsenhancements_datasheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheetsdetachmentabilities',
            old_name='datasheet_id',
            new_name='datasheet',
        ),
    ]
