# Generated by Django 4.2.17 on 2025-01-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0032_rename_datasheet_id_datasheetsdetachmentabilities_datasheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetsleader',
            name='attached_id',
        ),
        migrations.RemoveField(
            model_name='datasheetsleader',
            name='leader_id',
        ),
        migrations.AddField(
            model_name='datasheetsleader',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_ids', to='army_details.datasheets'),
        ),
        migrations.AddField(
            model_name='datasheetsleader',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_ids', to='army_details.datasheets'),
        ),
    ]
