# Generated by Django 4.2.17 on 2025-01-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0033_remove_datasheetsleader_attached_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdated',
            name='last_updated_date',
            field=models.DateField(unique=True),
        ),
    ]
