# Generated by Django 4.2.17 on 2025-01-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0035_remove_lastupdated_last_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastupdated',
            old_name='id',
            new_name='date',
        ),
    ]
