# Generated by Django 4.2.17 on 2025-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0036_rename_id_lastupdated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastupdated',
            name='id',
            field=models.BigAutoField(auto_created=True, default='2025-01-01 14:03:11', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastupdated',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
