# Generated by Django 4.2.17 on 2025-01-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0037_lastupdated_id_alter_lastupdated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUpdated',
        ),
    ]
