# Generated by Django 4.2.17 on 2025-01-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0039_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdated',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
