# Generated by Django 4.2.17 on 2025-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0040_alter_lastupdated_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdated',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
