# Generated by Django 4.2.17 on 2025-01-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0041_alter_lastupdated_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUpdated',
        ),
    ]
