# Generated by Django 4.2.17 on 2025-01-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0043_lastupdated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastUpdated',
        ),
    ]
