# Generated by Django 4.2.17 on 2025-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_details', '0044_delete_lastupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
